# Generated by Django 2.1.5 on 2019-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190828_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='编号'),
        ),
    ]
