# Generated by Django 2.1.5 on 2019-08-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190828_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='desc',
            new_name='description',
        ),
    ]
