# Generated by Django 2.1.5 on 2019-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190828_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='编号'),
        ),
    ]
