# Generated by Django 2.1.5 on 2019-08-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190829_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id'], 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
