# Generated by Django 2.1.5 on 2019-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('system', '0006_auto_20190829_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='角色'),
        ),
    ]
