# Generated by Django 2.1.5 on 2019-08-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20190830_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id'], 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
