# Generated by Django 2.1.5 on 2019-08-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20190831_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id'], 'permissions': (('can change password', 'change_password'), ('can enable user', 'enable_user'), ('can disable user', 'disable_user')), 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
