# Generated by Django 2.1.5 on 2019-08-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20190831_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id'], 'permissions': (('change_password', 'can change password'), ('enable_user', 'can enable user'), ('disable_user', 'can disable user')), 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
