# Generated by Django 2.1.5 on 2019-08-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20190831_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='code',
        ),
    ]
