# Generated by Django 2.1.5 on 2019-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_remove_menu_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='private_password',
            field=models.CharField(max_length=128, null=True, verbose_name='私有密码'),
        ),
    ]
