# Generated by Django 2.1.5 on 2019-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_instructor_private_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='mobile',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
