# Generated by Django 2.1.5 on 2019-09-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20190901_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id'], 'permissions': (('change_password', '基础数据.教师.修改密码'), ('enable_user', '基础数据.教师.启用用户'), ('disable_user', '基础数据.教师.禁用用户')), 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
