# Generated by Django 2.1.5 on 2019-08-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='desc',
            new_name='description',
        ),
    ]
