# Generated by Django 2.1.5 on 2019-09-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_time', models.DateTimeField(verbose_name='缺打卡时间')),
                ('check_in_period', models.CharField(choices=[('上午上班', '上午上班'), ('上午下班', '上午下班'), ('下午上班', '下午上班'), ('下午下班', '下午下班')], max_length=8, verbose_name='打卡时段')),
                ('reason', models.CharField(max_length=256, verbose_name='缺打卡原因')),
                ('Witness', models.CharField(max_length=256, verbose_name='缺打卡事由')),
                ('appler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '缺打卡申请',
                'verbose_name_plural': '缺打卡申请',
            },
        ),
    ]
