# Generated by Django 2.1.5 on 2019-09-01 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nocheckin',
            old_name='Witness',
            new_name='witness',
        ),
        migrations.AddField(
            model_name='nocheckin',
            name='crdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 17, 32, 33, 314352), verbose_name='创建时间'),
        ),
    ]
