# Generated by Django 2.1.5 on 2019-09-01 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_auto_20190901_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoCheckInLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('提出申请', '1'), ('部门主管处理', '2'), ('校区主任处理', '3'), ('审批完毕', '4')], max_length=2, verbose_name='步骤')),
                ('view_time', models.DateTimeField(null=True, verbose_name='查看时间')),
                ('handle_time', models.DateTimeField(null=True, verbose_name='处理时间')),
                ('result', models.CharField(choices=[('同意', '1'), ('不同意', '2')], max_length=2, null=True, verbose_name='处理结果')),
                ('opinion', models.CharField(max_length=256, null=True, verbose_name='处理结果')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
        ),
        migrations.AddField(
            model_name='nocheckin',
            name='cur_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_check_in_cur_handler', to=settings.AUTH_USER_MODEL, verbose_name='应处理人'),
        ),
        migrations.AddField(
            model_name='nocheckin',
            name='cur_step',
            field=models.CharField(choices=[('提出申请', '1'), ('部门主管处理', '2'), ('校区主任处理', '3'), ('审批完毕', '4')], default=1, max_length=2, verbose_name='处理步骤'),
        ),
        migrations.AddField(
            model_name='nocheckin',
            name='result',
            field=models.CharField(choices=[('同意', '1'), ('不同意', '2')], default=1, max_length=2, verbose_name='处理结果'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='appler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_check_in_applyer', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='check_in_period',
            field=models.CharField(choices=[('上午上班', '1'), ('上午下班', '2'), ('下午上班', '3'), ('下午下班', '4')], max_length=2, verbose_name='打卡时段'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='crdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='nocheckinlog',
            name='no_check_in_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.NoCheckIn', verbose_name='缺打卡申请ID'),
        ),
    ]
