# Generated by Django 2.1.5 on 2019-09-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190901_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nocheckinlog',
            old_name='no_check_in_id',
            new_name='NoCheckIn',
        ),
    ]
