# Generated by Django 2.1.5 on 2019-09-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190901_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nocheckinlog',
            old_name='NoCheckIn',
            new_name='nocheckin',
        ),
    ]
