# Generated by Django 2.1.5 on 2019-09-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20190902_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nocheckin',
            options={'permissions': (('process_nocheckin', '行政人事.考勤管理.缺打卡.处理申请'), ('view_all_nocheckin', '行政人事.考勤管理.缺打卡.查看所有申请'), ('view_deprtment_nocheckin', '行政人事.考勤管理.缺打卡.查看本部门申请')), 'verbose_name': '缺打卡申请', 'verbose_name_plural': '缺打卡申请'},
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='result',
            field=models.CharField(choices=[('处理中...', '0'), ('同意', '1'), ('不同意', '2')], default=1, max_length=2, verbose_name='处理结果'),
        ),
    ]
