# Generated by Django 2.1.5 on 2019-09-03 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20190902_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nocheckinlog',
            name='handle_time',
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='check_in_period',
            field=models.CharField(choices=[('1', '上午上班'), ('2', '上午下班'), ('3', '下午上班'), ('4', '下午下班')], max_length=2, verbose_name='打卡时段'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='cur_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_check_in_cur_handler', to=settings.AUTH_USER_MODEL, verbose_name='应审核人'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='cur_step',
            field=models.CharField(choices=[('1', '提出申请'), ('2', '部门主管处理'), ('3', '校区主任处理'), ('4', '审批完毕')], default=1, max_length=2, verbose_name='处理步骤'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='result',
            field=models.CharField(choices=[('0', '处理中...'), ('1', '同意'), ('2', '不同意')], default=1, max_length=2, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='nocheckinlog',
            name='opinion',
            field=models.CharField(max_length=256, null=True, verbose_name='审核意见'),
        ),
        migrations.AlterField(
            model_name='nocheckinlog',
            name='result',
            field=models.CharField(choices=[('同意', '1'), ('不同意', '2')], max_length=2, null=True, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='nocheckinlog',
            name='step',
            field=models.CharField(choices=[('1', '提出申请'), ('2', '部门主管处理'), ('3', '校区主任处理'), ('4', '审批完毕')], max_length=2, verbose_name='步骤'),
        ),
    ]
