# Generated by Django 2.1.5 on 2019-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_nocheckinlog_handle_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nocheckinlog',
            name='result',
        ),
        migrations.AddField(
            model_name='nocheckinlog',
            name='is_agree',
            field=models.CharField(choices=[('同意', '1'), ('不同意', '0')], max_length=2, null=True, verbose_name='是否同意'),
        ),
    ]
