# Generated by Django 2.1.5 on 2019-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20190903_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nocheckin',
            name='check_in_period',
            field=models.IntegerField(choices=[('1', '上午上班'), ('2', '上午下班'), ('3', '下午上班'), ('4', '下午下班')], max_length=2, verbose_name='打卡时段'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='cur_step',
            field=models.IntegerField(choices=[('1', '提出申请'), ('2', '部门主管处理'), ('3', '校区主任处理'), ('4', '审批完毕')], default=1, max_length=2, verbose_name='处理步骤'),
        ),
        migrations.AlterField(
            model_name='nocheckin',
            name='result',
            field=models.IntegerField(choices=[('0', '处理中...'), ('1', '同意'), ('2', '不同意')], default=1, max_length=2, verbose_name='审核结果'),
        ),
    ]
