# Generated by Django 2.1.5 on 2019-09-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0012_auto_20190906_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nocheckinlog',
            old_name='handler',
            new_name='processer',
        ),
        migrations.RemoveField(
            model_name='nocheckin',
            name='cur_handler',
        ),
        migrations.AddField(
            model_name='nocheckin',
            name='cur_processer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_check_in_cur_processer', to=settings.AUTH_USER_MODEL, verbose_name='应审核人'),
        ),
    ]
