# Generated by Django 2.1.5 on 2019-09-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0014_auto_20190906_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('leave_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='请假时长')),
                ('leave_type', models.IntegerField(choices=[(1, '病假'), (2, '事假'), (3, '婚假'), (4, '产假'), (5, '父亲假'), (6, '工伤假'), (7, '丧假'), (8, '调休')], verbose_name='请假类型')),
                ('reason', models.CharField(max_length=256, verbose_name='请假原因')),
                ('step', models.IntegerField(choices=[(1, '提出申请'), (2, '部门主管处理'), (3, '校区主任处理'), (0, '审批完毕')], verbose_name='处理步骤')),
                ('result', models.IntegerField(choices=[(0, '处理中...'), (1, '同意'), (2, '不同意')], verbose_name='审核结果')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'permissions': (('process_leave', '行政人事.考勤管理.请假.处理申请'), ('view_all_leave', '行政人事.考勤管理.请假.查看所有申请'), ('view_deprtment_leave', '行政人事.考勤管理.请假.查看本部门申请')),
            },
        ),
    ]
