# Generated by Django 2.1.5 on 2019-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='handle_time',
            new_name='process_time',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_hours',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='请假时长'),
        ),
    ]
