# Generated by Django 2.1.5 on 2019-09-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0017_auto_20190907_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_time', models.DateTimeField(verbose_name='缺打卡时间')),
                ('check_in_period', models.IntegerField(choices=[(1, '上午上班'), (2, '上午下班'), (3, '下午上班'), (4, '下午下班')], verbose_name='打卡时段')),
                ('reason', models.CharField(max_length=256, verbose_name='缺打卡原因')),
                ('witness', models.CharField(max_length=256, verbose_name='缺打卡事由')),
                ('step', models.IntegerField(choices=[(1, '提出申请'), (2, '部门主管处理'), (3, '校区主任处理'), (4, '审批完毕')], verbose_name='处理步骤')),
                ('result', models.IntegerField(choices=[(0, '处理中...'), (1, '同意'), (2, '不同意')], verbose_name='审核结果')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_check_in_applyer', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_check_in_auditor', to=settings.AUTH_USER_MODEL, verbose_name='应审核人')),
            ],
            options={
                'verbose_name': '缺打卡申请',
                'verbose_name_plural': '缺打卡申请',
                'permissions': (('process_nocheckin', '行政人事.考勤管理.缺打卡.处理申请'), ('view_all_nocheckin', '行政人事.考勤管理.缺打卡.查看所有申请'), ('view_deprtment_nocheckin', '行政人事.考勤管理.缺打卡.查看本部门申请')),
            },
        ),
    ]
