# Generated by Django 2.1.5 on 2019-09-08 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0021_auto_20190908_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('outwork_hours', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='外勤时长')),
                ('address', models.CharField(max_length=256, verbose_name='外勤地点')),
                ('reason', models.CharField(max_length=256, verbose_name='外勤原因')),
                ('step', models.IntegerField(choices=[(1, '提出申请'), (2, '部门主管处理'), (3, '校区主任处理'), (4, '审批完毕')], verbose_name='处理步骤')),
                ('result', models.IntegerField(choices=[(0, '处理中...'), (1, '同意'), (2, '不同意')], verbose_name='审核结果')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwork_applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outwork_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '外勤申请',
                'verbose_name_plural': '外勤申请',
                'permissions': (('process_outwork', '行政人事.考勤管理.外勤.处理申请'), ('view_all_outwork', '行政人事.考勤管理.外勤.查看所有申请'), ('view_deprtment_outwork', '行政人事.考勤管理.外勤.查看本部门申请')),
            },
        ),
    ]
