# Generated by Django 2.1.5 on 2019-09-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0022_outwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('breakoff_hours', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='调休时长')),
                ('reason', models.CharField(max_length=256, verbose_name='调休原因')),
                ('step', models.IntegerField(choices=[(1, '提出申请'), (2, '部门主管处理'), (3, '校区主任处理'), (4, '审批完毕')], verbose_name='处理步骤')),
                ('result', models.IntegerField(choices=[(0, '处理中...'), (1, '同意'), (2, '不同意')], verbose_name='审核结果')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakoff_applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakoff_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '调休申请',
                'verbose_name_plural': '调休申请',
                'permissions': (('process_breakoff', '行政人事.考勤管理.调休.处理申请'), ('view_all_breakoff', '行政人事.考勤管理.调休.查看所有申请'), ('view_deprtment_breakoff', '行政人事.考勤管理.调休.查看本部门申请')),
            },
        ),
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('destination', models.CharField(max_length=256, verbose_name='目的地')),
                ('reason', models.CharField(max_length=256, verbose_name='出差原因')),
                ('expected_result', models.CharField(max_length=512, verbose_name='预计归来的结果')),
                ('required_support', models.CharField(max_length=512, verbose_name='所需支持')),
                ('step', models.IntegerField(choices=[(1, '提出申请'), (2, '部门主管处理'), (3, '校区主任处理'), (4, '审批完毕')], verbose_name='处理步骤')),
                ('result', models.IntegerField(choices=[(0, '处理中...'), (1, '同意'), (2, '不同意')], verbose_name='审核结果')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesstrip_applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesstrip_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '出差申请',
                'verbose_name_plural': '出差申请',
                'permissions': (('process_businesstrip', '行政人事.考勤管理.出差.处理申请'), ('view_all_businesstrip', '行政人事.考勤管理.出差.查看所有申请'), ('view_deprtment_businesstrip', '行政人事.考勤管理.出差.查看本部门申请')),
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_time', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='剩余调休时长')),
                ('adjust_time', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='本次调整时长')),
                ('adjust_reason', models.CharField(max_length=256, verbose_name='调整原因')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_instructor', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '调休信息',
                'verbose_name_plural': '调休信息',
                'permissions': (('view_all_Vacation', '行政人事.考勤管理.调休信息.查看所有'), ('view_deprtment_Vacation', '行政人事.考勤管理.调休信息.查看本部门')),
            },
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='module_id',
            field=models.IntegerField(choices=[(1, '缺打卡'), (2, '请假'), (3, '加班'), (4, '外勤'), (5, '出差'), (6, '调休')], verbose_name='模块ID'),
        ),
    ]
