# Generated by Django 2.1.5 on 2019-09-08 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0023_auto_20190908_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_time', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='剩余调休时长')),
                ('adjust_time', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='本次调整时长')),
                ('adjust_reason', models.CharField(max_length=256, verbose_name='调整原因')),
                ('crdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacationlog_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacationlog_instructor', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
        ),
    ]
